providers = ["python"]

[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = ["...", "cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "bash start.sh"
